[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["sub_api"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "sub_api"
  org = "sajithekanayaka"
  version = "3.1.1"

