openapi: 3.0.1
info:
  title: /
  version: 3.1.1
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "8090"
paths:
  /:
    get:
      operationId: get
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
